name = "netflix-jikkyo-config"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
LIVE_RELAY = "false"
RELAY_ENDPOINT = ""
RELAY_TITLE_IDS = ""
ANNOUNCEMENT = ""
MIN_VERSION = ""
NICO_BRIDGE_ENABLED = "true"
NICO_BRIDGE_LV_ID = "lv349946113"
NICO_BRIDGE_TITLE = ""
NICO_BRIDGE_TITLE_IDS = ""
NICO_OAUTH_CLIENT_ID = ""
NICO_OAUTH_CLIENT_SECRET = ""
